model:
  encoder_type: "vit"
  encoder_name: "google/vit-base-patch16-224-in21k"
  attention_type: "dot"
  d_model: 512
  num_layers: 4
  num_heads: 8

training:
  batch_size: 16
  lr: 1e-4
  num_epochs: 1
  max_len: 300

data:
  image_size: 320
  dataset_name: "deepcopy/MathWriting-human"